### ISSUE TITLE
M01 - Añadir contraseña

### ISSUE THREAD

**Issue by pyeom** [INF331/tarea1#7]
Permite al usuario añadir una contraseña para la aplicación que el mismo especifique.

**Comment by FAo-o** [comment]
La contraseña solicita, debe cumplir con ciertos estándares acordados por el equipo 
Dichos entandares deberia ser la longitud, cantidad de caracteres especiales, cantidad de mayúsculas y cantidad de caracteres numéricos.

**Comment by FAo-o** [comment]
La contraseña debe estar asociada a una plataforma y correo.
